### ISSUE TITLE
Displaying text notification for count Zero styling violations

### ISSUE THREAD

**Issue by muthu-tech** [PyCQA/flake8#1373]
I'm reporting, a user experience improvement suggestion
The code that I'm using via pip install is seen in,
https://github.com/PyCQA/flake8/

_How I installed Flake8_

$ pip install flake8

**Improvement Proposal**
While I run flake8 <python_code_location> --config=setup.cfg --count --show-source --statistics

I get notified of Python styling violations (customized in setup.cfg per our needs) and thanks for this excellent tool. However, while I resolve all those violations and finally bring down the count to 0, I am just being notified as 0  without any text message.
So I thought in /flake8/main/application.py, in the exit method, following could be added to enhance a bit on the user experience.
```
        if self.options.count:
            print(self.result_count)

           **if self.result_count == 0:
              print("Sweet ! Zero styling violations found in your code")**
```

Please let me know if this seems a valid user experience improvement request.

Thanks,
Muthu

**Comment by asottile** [comment]
I don't think this improves anything -- just adds nose, and has been proposed before

**Comment by jheiss** [comment]
(FWIW it looks like the previous proposal is #634, just to link the two issues.)

Would you be willing to make this optional behavior that users could enable?

black is very fancy, maybe too much so:

```
$ black tests
All done! ✨ 🍰 ✨
7 files left unchanged.
```

mypy is a bit simpler:

```
$ mypy tests
Success: no issues found in 7 source files
```

Whereas flake8 just says nothing. I'd like to have it say something so that I can easily scan the output of these various commands and confirm that everything is happy. I'm fine if it isn't the default behavior, I can imagine that you wouldn't want to change the default at this point anyway.

**Comment by asottile** [comment]
you can write a formatter to add noise if you want -- it will not be part of core
