### ISSUE TITLE
Any interest in owning a flake8 extension for VS Code?

### ISSUE THREAD

**Issue by brettcannon** [PyCQA/flake8#1467]
For the [Python extension for VS Code](https://marketplace.visualstudio.com/items?itemName=ms-python.python), we are embarking on redoing our tool support as separate extensions (using [LSP](https://microsoft.github.io/language-server-protocol/) for a better experience than what we currently provide). One of those tools is flake8, and before we publish a standalone flake8 extension we wanted to see if you had any interest in owning the flake8 extension?

We already have a prototype mostly working and expect to finish the work before the end of the year, but since transferring ownership on the [VS Code Marketplace](https://marketplace.visualstudio.com/vscode) is a pain and some projects like owning their editor experience, we thought we would ask first if you had any interest in owning the extension as a courtesy before we published anything (we would give you the working code we have if you wanted it)? There's no expectations here and we are fully prepared to create and own the extension if you are not interested in this.

**Comment by asottile** [comment]
what would the maintenance look like -- I don't think either of us are really well equipped to take on a typescript project to maintain this -- if the microsoft python team is comfortable maintaining it for now that seems fine

**Comment by brettcannon** [comment]
We are actually planning on using this extension to develop a (cookiecutter | GH repo) template for Python-based extensions that will minimize the amount of TypeScript you have to write to zero; our prototype only requires editing JSON (`package.json`), anything special necessary on the language server side (which is entirely Python), and appropriate tests (which would be run by pytest).

If you're more comfortable with us starting with ownership we can. Ownership transfers of extensions are doable with effort, so this won't close a door on anything. Basically if you have any reservations I would rather keep it on our side and have you provide feedback/guidance on the experience so no one feels pressured to do anything.

Another option is to work with you on developing an LSP interface for flake8 and then we simply wrap that in a VS Code extension. That way more editors can benefit from the work directly. That could be in flake8 directly or a separate package, whatever you prefer.

Or you can just see how it turns out with our initial work and then come back to us to talk about breaking out the LSP bit if that's a part you would like to own as that's easy to separate out later. If you think that might interest you we can make sure to not publish anything to PyPI until we make our first extension release and talk to you about the resulting implementation.

**Comment by asottile** [comment]
yeah probably best for it to be done externally for now and we can circle back at a later time

**Comment by karthiknadig** [comment]
@asottile We are further along in the process of building linting over language server protocol. Here is a prototype of the extension if you can try, to get an idea of what we are planning. You can download it, extract the `.vsix` file, and then [install the VSIX](https://code.visualstudio.com/docs/editor/extension-marketplace#_install-from-a-vsix) to try it out.

Please try this out with python 3.10, the extension is bundled with flake8 4.0.1 (you should not have to install flake8): 
[python-flake8.zip](https://github.com/PyCQA/flake8/files/8046041/python-flake8.zip)
 

For some code like this:
```python
import unittest
import re

class TestSum(unittest.TestCase):

    def test_sum(self):
        self.assertEqual(sum([10, 20, 30]), 60, "Should be 60")

    def test_sum_tuple(self):
        self.assertEqual(sum((10, 20, 30)), 60, "Should be 60")

if __name__ == '__main__':
    unittest.main()
```
you should see:
![image](https://user-images.githubusercontent.com/3840081/153539680-f2267470-167f-4be3-a52c-31c27e1da54b.png)

**Comment by asottile** [comment]
@karthiknadig bundling flake8 concerns me -- users will expect that the version they're using in their terminal will match what's run in their editor

**Comment by brettcannon** [comment]
The shipped version is only a fallback for users who don't have flake8 already installed (i.e. beginners who are just trying to get going and have been told to "use flake8").

**Comment by asottile** [comment]
one thing to note, I see that there are different icons for F/E/W -- these don't actually indicate failure, error, or warning -- they are just prefixes for codes.  they should all display at the "error" level probably

**Comment by karthiknadig** [comment]
@asottile That can be configured using the `python.flake8Severity` setting. We have people requesting control over what icons are shown see here https://github.com/microsoft/vscode-python/issues/18261

This is the default setting:
```
"python.flake8Severity": {
    "E": "Error",
    "F": "Error",
    "I": "Information",
    "W": "Warning"
}
```
The above extension allows you to control it further:
```{
    "E": "Error",
    "F": "Error",
    "I": "Information",
    "W": "Warning",
    "E501": "Warning"
}
```

**Comment by asottile** [comment]
please set them all to `Error` by default, and `I` is not a code provided by flake8 by default

**Comment by sigmavirus24** [comment]
Yeah the I prefix is shared by a few plugins iirc and can not be reliably classified one way or another. If error is too severe, making everything a warning would be more sensible

**Comment by jaklan** [comment]
@karthiknadig @brettcannon I see the new extension has exactly the same problem as the current built-in implementation - `python.flake8Path` doesn't accept the name of the executable to run, so you can't just specify e.g. `flake8` - you need to specify the full path instead of just allowing `PATH` to do the job.

What's the actual use-case?  All the tools like `black`, `mypy`, `tox`, `pytest`, `isort`, `coverage` etc. provide support for `pyproject.toml`-based configuration, as it becomes a standard approach nowadays to maintain only one file. All, but not `flake8`, as @asottile continues his fight against TOML (and yes, I know the [thread](https://github.com/PyCQA/flake8/issues/234), but sorry - other maintainers were able to add the support, in a native way or the legacy one like `tox`, but @asottile is the only one who prefers to stay against the community just because of his personal crusade, even when the [PR](https://github.com/PyCQA/flake8/pull/1332) was already done).

It's extremely annoying attitude, but anyway - there's a solution for that: [`pflake8`](https://github.com/csachs/pyproject-flake8), so the flake8 wrapper, which adds the support for `pyproject.toml`. It works pretty well also with VS Code, but because of the above issue - I need to provide the full path like `./.venv/bin/pflake8`, which makes the config tied to the very concrete venv, so I can't set it globally as `pflake8` to allow finding that on `PATH`, I also can't keep the workspace-level `settings.json` in a generic form, shareable with other teammates.
