### ISSUE TITLE
Plugin name restriction does not match documentation

### ISSUE THREAD

**Issue by televi** [PyCQA/flake8#1645]
### how did you install flake8?

```console
pip install flake8
```

### unmodified output of `flake8 --bug-report`

```json
There was a critical error during execution of Flake8:
plugin code for `flake8-copyright[flake8_copyright]` does not match ^[A-Z]{1,3}[0-9]{0,3}$
```

#### what I expected to happen

flake8 runs

#### commands ran

```console
$ flake8 .
```

#### what I get

There was a critical error during execution of Flake8:
plugin code for `flake8-copyright[flake8_copyright]` does not match ^[A-Z]{1,3}[0-9]{0,3}$

#### details

The docs under docs/source/plugin-development/registering-plugins.rst simply says that one should _consider_ using 3 cap alpha plus 3 nums - it does not say it is mandatory nor provide the regex that flake8 will use to validate the entry point.  This new(?) requirement breaks (for example) flake8-copyright.

The exact text from the docs is:

**Please Note:** Your entry point does not need to be exactly 4 characters
as of |Flake8| 3.0. *Consider using an entry point with 3 letters followed
by 3 numbers (i.e.* ``ABC123`` *).*

If flake8 v5 is now enforcing that the plugins must register their entry point as a string of 1-3 capital letters followed by 0-3 numerals, then that should be clearly stated in the docs.

**Comment by asottile** [comment]
prior to flake8 3.x the requirement was `[A-Z][0-9]{3}` in 3.0 it was extended to `[A-Z]{1,3}[0-9]{1,3}` -- in 5.0 it was enforced since it was silently allowing incorrect behaviour before

the docs do clearly state that this is how plugins are named and that was not changed: https://flake8.pycqa.org/en/latest/plugin-development/registering-plugins.html

**Comment by televi** [comment]
@asottile - perhaps I'm not understanding then what the phrase "Consider using an entry point..." is refering to?  I don't see anything in the docs that list the regex, for example.  For me, that would make it much clearer than just a few examples (which don't actually encompass the breadth of the regex).

When I look at flake8-black, for example, they use an entry point of 'BLK' - the examples in the docs don't really reflect that such a name is acceptable, nor that BLACK would not be acceptable.  What am I missing in the docs that would show that the former is fine but the latter is not?

**Comment by asottile** [comment]
if you don't understand then send a patch to the docs which you think would be better -- I don't have your perspective since I remember the days when it could only be 1 letter and remember when it was extended to 3

as it is right now it sounds more like you're complaining about the restriction and nitpicking the docs which isn't productive

**Comment by televi** [comment]
I appologize if it sounds like I'm complaining about the restriction - that was very much not my intent.  My plan was to fork and fix the plugin that is broken (since it seems unmaintained but we use it pretty extensively) and I was trying to understand what change I needed to make to that plugin to fix it.

I'll submit a patch as you suggested for the docs.

**Comment by asottile** [comment]
I'll give you the benefit of the doubt, but when you see an error message like `plugin code for `flake8-copyright[flake8_copyright]` does not match ^[A-Z]{1,3}[0-9]{0,3}$` -- I don't know how you could possibly be confused about what's wrong

**Comment by sigmavirus24** [comment]
> I appologize if it sounds like I'm complaining about the restriction - that was very much not my intent.  My plan was to fork and fix the plugin that is broken (since it seems unmaintained but we use it pretty extensively) and I was trying to understand what change I needed to make to that plugin to fix it.
> 
> I'll submit a patch as you suggested for the docs.

I don't understand what's confusing to you and I'm not sure you do. Given that, what are you planning to change in the documentation? Are you going to introduce the regular expression which could change and then have to be updated in two places leading almost certainly to a true documentation disconnect?

**Comment by televi** [comment]
@asottile - I think I see where I introduced the confusion.  The error message is fine - what I was trying to point out was that the documentation for first time plugin authors didn't reflect that same requirement.  Nothing more than that.  When I read that document, I didn't find anything about the regex and that caused me to wonder if the error was due to a new requirement since it worked in flake8 v4.  Your explanataions cleared that up perfectly.

@sigmavirus24 - I think I understand what's confusing me (philosophical debates aside) 😄 .   I had planned to add the regex but would be happy to instead add a pointer to the code that enforces it to avoid having to update it in multiple places.  I beleive the code fragment in question would be in src/flake8/plugins/finder.py and is the constant VALID_CODE.

**Comment by sigmavirus24** [comment]
It depends on where you're adding this documentation 😂

I tried to have a distinction between user documentation (which shouldn't care about this, I'd think), and maintainer documentation (where this might not fit?)

I think the sentence could be clarified. It was written to suggest people use up to these characters to avoid conflicts since single-letter prefixes were causing conflicts when people installed multiple plugins.

As (I think) the author of that paragraph I'm not sure it alone needs to convey all of the information but small changes could make this clearer. Something like "Single-letter prefixes have caused lots of issues. Consider using two- or three-letter prefixes to avoid stepping on another plugin's prefix. **Note: three is currently the max letter prefix length**

**Comment by televi** [comment]
I agree re: user vs maintainer/plugin developer - it was speciifcally the plugin developer docs I was planning to update (registering-plugins.rst, specificaly and then only the "Please Note" portion at the end).  I do prefer the idea of describing the regex instead of listing it.

I'll submit a PR with what I think matches what you've suggested above - let me know if you'd like to see any changes to it.

**Comment by DevynCJohnson** [comment]
@asottile , why not add a command-line flag or environment variable that one can use if they wish to use flake8 plugins that this new "feature" forbids? As of now, flake8 out-of-the-box is useless to me. I now need modify it so that most flake8 plugins will work.

**Comment by asottile** [comment]
why would I add a `--silently-allow-incorrect-behaviour` flag? no.
