### ISSUE TITLE
plugins can break `--version` by calling `parse_args`

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#357]
In GitLab by @asottile on Apr 23, 2020, 17:58

see: https://github.com/deppen8/pandas-vet/issues/98

https://github.com/deppen8/pandas-vet/blob/cfd28ed97e452fca2f47f8d1b6509c12370860f9/pandas_vet/__init__.py#L105-L107

probably:

- produce a loud warning and move the functionality to an internal module-level function 
- remove the unintentionally-public methods in the next minor version

**Comment by sigmavirus24** [comment]
So I don't think removing `parse_args` from the manager is the solution here, but I'd be happy to discuss that. It's internal but I suspect what we really need is better plugin docs/examples for people to pull from because this is a "That is someone who didn't know the right thing to do" 

Also I'd love to rework plugins altogether in a future major version without dropping support for the old crufties until a few relesaes after we have a new API. The whole "use classmethods and store state on there and hope the fork method supports refreshing that" is nonsense and needs to change

**Comment by sigmavirus24** [comment]
The correct way to do this _is_ documented: https://flake8.pycqa.org/en/latest/plugin-development/plugin-parameters.html#accessing-parsed-options I don't believe it's worth keeping this open because someone failed to read the docs
