### ISSUE TITLE
Check files that have not .py extension but have python shebang

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#649]
In GitLab by @rubendibattista on Feb 24, 2018, 11:12

*Please describe how you installed Flake8*

`pip install flake8`

*Please provide the exact, unmodified output of `flake8 --bug-report`*
```
{
  "dependencies": [
    {
      "dependency": "setuptools", 
      "version": "38.4.1"
    }
  ], 
  "platform": {
    "python_implementation": "CPython", 
    "python_version": "2.7.14", 
    "system": "Linux"
  }, 
  "plugins": [
    {
      "is_local": false, 
      "plugin": "mccabe", 
      "version": "0.6.1"
    }, 
    {
      "is_local": false, 
      "plugin": "pycodestyle", 
      "version": "2.3.1"
    }, 
    {
      "is_local": false, 
      "plugin": "pyflakes", 
      "version": "1.6.0"
    }
  ], 
  "version": "3.5.0"
}
```

*Please describe the problem or feature*

By default `flake8` should check not only files that have `*.py` extension but also files that have a python shebang

E.g.
```
#!/usr/bin/env python
```

**Comment by asottile** [comment]
In GitLab by @rubendibattista on Feb 24, 2018, 11:12

changed the description

**Comment by asottile** [comment]
In GitLab by @jdufresne on Jun 6, 2018, 12:30

mentioned in merge request !241

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Oct 20, 2018, 10:22

!241 was merged, resolving this

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Oct 20, 2018, 10:22

closed

**Comment by asottile** [comment]
In GitLab by @rubendibattista on Oct 20, 2018, 10:55

Thx!

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Mar 1, 2019, 04:38

reopened

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Mar 1, 2019, 04:38

I was wrong about !241 being merged :grimacing:

**Comment by stefan6419846** [comment]
Has there been any recent progress on this? As far as I understand #884, there had been some objections against it due to potential performance issues, although one might argue that making this opt-in would allow each user to decide on its own. At the moment, these paths have to be specified manually (a complete exclude list might not be feasible as well).

I did have a short look at the old code (which had been linked inside the PR issue, as the original GitLab project does not seem to be accessible any more): https://github.com/PyCQA/flake8/compare/33e7eae53ad513952da777cabd3654219efe0eb8..fff3d0bfbeaccceb93223dc86bec4370084a3f2d. There has been some general refactoring of *flake8* in the meantime, which requires further changes, but from what I have seen, `flake8.discover_files.expand_paths.is_included` would basically need another `or` condition to check for executable files with shebangs to get the desired behavior.

**Comment by asottile** [comment]
given how complex and difficult this was to get even close to right in `pre-commit` this is not as simple as just another `or` -- I don't think `flake8` should attempt this
